Repository cesium/codeweek18, pull requests merged in 2018-09, with the labels that each got.

#2 Centrado o primeiro slide com o logo da codeweek e a data
  _includes/header.html
  _sass/_carousel.scss
Labels: bug

#11 Migrate to fontawesome
  _includes/counter.html
  _includes/elements.html
  _includes/event.html
  _includes/footer.html
  _includes/gallery.html
  _includes/head.html
  _includes/header.html
  _includes/questions.html
  _includes/services.html
  _includes/speakers.html
  _includes/subscribe.html
  _sass/_carousel.scss
  _sass/_footer.scss
  _sass/fontawesome/_animated.scss
  _sass/fontawesome/_bordered-pulled.scss
  _sass/fontawesome/_core.scss
  _sass/fontawesome/_fixed-width.scss
  _sass/fontawesome/_icons.scss
  _sass/fontawesome/_larger.scss
  _sass/fontawesome/_list.scss
  _sass/fontawesome/_mixins.scss
  _sass/fontawesome/_rotated-flipped.scss
  _sass/fontawesome/_screen-reader.scss
  _sass/fontawesome/_shims.scss
  _sass/fontawesome/_stacked.scss
  _sass/fontawesome/_variables.scss
  _sass/fontawesome/brands.scss
  _sass/fontawesome/fontawesome.scss
  _sass/fontawesome/regular.scss
  _sass/fontawesome/solid.scss
  _sass/fontawesome/v4-shims.scss
  assets/css/main.scss
  assets/fonts/LineIcons.eot
  assets/fonts/LineIcons.svg
  assets/fonts/LineIcons.ttf
  assets/fonts/LineIcons.woff
  assets/fonts/fa-brands-400.eot
  assets/fonts/fa-brands-400.svg
  assets/fonts/fa-brands-400.ttf
  assets/fonts/fa-brands-400.woff
  assets/fonts/fa-brands-400.woff2
  assets/fonts/fa-regular-400.eot
  assets/fonts/fa-regular-400.svg
  assets/fonts/fa-regular-400.ttf
  assets/fonts/fa-regular-400.woff
  assets/fonts/fa-regular-400.woff2
  assets/fonts/fa-solid-900.eot
  assets/fonts/fa-solid-900.svg
  assets/fonts/fa-solid-900.ttf
  assets/fonts/fa-solid-900.woff
  assets/fonts/fa-solid-900.woff2
  assets/fonts/line-icons.css
  index.html
Labels: enhancement, good first issue

#13 Fix schedule section
  _data/schedule.yml
  _includes/schedule.html
Labels: bug

#15 Fix Google Map section
  _includes/map.html
  _includes/scripts.html
  _sass/_contact.scss
  _sass/_responsive.scss
  assets/js/map.js
  index.html
Labels: bug, enhancement
